- hosts: web
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest image
      command: docker pull yagami168/vue-app:latest

    - name: Stop old container
      command: docker stop vue-container
      ignore_errors: yes

    - name: Remove old container
      command: docker rm vue-container
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name vue-container -p 3000:80 yagami168/vue-app:latest