server {
    listen 80;

    server_name loengpheaktra.xyz www.loengpheaktra.xyz;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        try_files $uri $uri/ /index.html;
    }
}